name: Helix-Code-Review

on:
  pull_request:
    branches:
      - master

jobs:
  add_pr_comment:
    name: Helix Code
    runs-on: ubuntu-latest

    env:
      GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      REPOSITORY_NAME: ${{ github.repository }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      LINK: "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
      FILE_SUMMARY: false
      TEST_SUMMARY: false
      BUG_SUMMARY: false
      RISK_SUMMARY: false
      RISK_BREAKING: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install gpt-review
        shell: bash
        run: |
            sudo apt-get update
            python3 -m venv .env
            source .env/bin/activate
            python -m pip install --upgrade pip
            python -m pip install langchain==0.0.301
            python -m pip install pydantic==1.10.13
            python -m pip install gpt-review==v0.9.5
            python -m pip install llama-index==0.10.39
            python -m pip install openai
            gpt ask "hello"

      - name: Run GPT review
        run: |
          source .env/bin/activate
          gpt github review \
            --access-token $GITHUB_TOKEN \
            --pull-request $PR_NUMBER \
            --repository $REPOSITORY_NAME
        continue-on-error: true

      - name: Run additional review
        run: |
          source .env/bin/activate
          gpt github review \
            --access-token $GITHUB_TOKEN \
            --pull-request $PR_NUMBER \
            --repository $REPOSITORY_NAME