name: 'Helix Code Review'

on:
  workflow_call:
    secrets:
      OPENAI_API_KEY:
        description: 'OpenAI API Key'
        required: true
    inputs:
      PATCH_PR:
        description: 'Pull Request Number'
        required: true
        type: string
      PATCH_REPO:
        description: 'GitHub Repository'
        required: true
        type: string
      CACHE_KEY:
        description: 'A unique key for caching dependencies'
        required: false
        type: string

jobs:
  gpt_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install gpt-review
        shell: bash
        run: |
          sudo apt-get update
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
          python -m pip install langchain==0.0.301
          python -m pip install pydantic==1.10.13
          python -m pip install gpt-review==v0.9.5

      - name: Run gpt-review
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
            gpt github review \
              --access-token $GITHUB_ACCESS_TOKEN \
              --pull-request ${{ github.event.pull_request.number }} \
              --repository ${{ github.repository }}